CREATE TABLE research_metrics (
  id SERIAL PRIMARY KEY,
  run_at TIMESTAMPTZ DEFAULT NOW(),
  n_observations INTEGER,
  ff5_alpha DOUBLE PRECISION,
  ff5_alpha_tstat DOUBLE PRECISION,
  ff5_alpha_pval DOUBLE PRECISION,
  ff5mom_alpha DOUBLE PRECISION,
  ff5mom_alpha_tstat DOUBLE PRECISION,
  ff5mom_alpha_pval DOUBLE PRECISION,
  smb_loading DOUBLE PRECISION,
  full_sample_median_30d DOUBLE PRECISION,
  full_sample_median_90d DOUBLE PRECISION,
  full_sample_median_180d DOUBLE PRECISION,
  filtered_median_30d DOUBLE PRECISION,
  filtered_median_90d DOUBLE PRECISION,
  filtered_median_180d DOUBLE PRECISION,
  hit_rate DOUBLE PRECISION,
  avg_winner DOUBLE PRECISION,
  avg_loser DOUBLE PRECISION,
  payoff_ratio DOUBLE PRECISION,
  jackknife_p05_pct DOUBLE PRECISION,
  jackknife_p10_pct DOUBLE PRECISION,
  spearman_rho DOUBLE PRECISION,
  spearman_pval DOUBLE PRECISION,
  permutation_pval DOUBLE PRECISION,
  era_pre2013_n INTEGER,
  era_pre2013_alpha DOUBLE PRECISION,
  era_pre2013_pval DOUBLE PRECISION,
  era_2013_2019_n INTEGER,
  era_2013_2019_alpha DOUBLE PRECISION,
  era_2013_2019_pval DOUBLE PRECISION,
  era_post2019_n INTEGER,
  era_post2019_alpha DOUBLE PRECISION,
  era_post2019_pval DOUBLE PRECISION
);
